/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef master_slave_CONSTANTS_H
#define master_slave_CONSTANTS_H

#include "master_slave_types.h"



class master_slaveConstants {
 public:
  master_slaveConstants();

};

extern const master_slaveConstants g_master_slave_constants;



#endif
