/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "master_slave_constants.h"



const master_slaveConstants g_master_slave_constants;

master_slaveConstants::master_slaveConstants() {
}



